# Generated by Django 5.2.8 on 2025-11-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='bonus_per_minuman',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='miuman_terjual',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='jenis',
        ),
        migrations.CreateModel(
            name='barista',
            fields=[
                ('pegawai_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.pegawai')),
                ('bonus_per_minuman', models.IntegerField(default=0)),
                ('miuman_terjual', models.IntegerField(default=0)),
            ],
            bases=('employees.pegawai',),
        ),
    ]
